"""Real subjects: SKA's catalogue topics grouped into full, textbook-sized subjects.
Each real subject is one SKA textbook; each existing topic becomes a chapter in it.
Fields follow UNESCO ISCED-F 2013 broad fields. Edit this file to move topics; run it to
regenerate map/real_subjects.json."""
import json, sys
F = {"00":"Generic programmes and qualifications","01":"Education","02":"Arts and humanities",
     "03":"Social sciences, journalism and information","04":"Business, administration and law",
     "05":"Natural sciences, mathematics and statistics","06":"Information and communication technologies",
     "07":"Engineering, manufacturing and construction","08":"Agriculture, forestry, fisheries and veterinary",
     "09":"Health and welfare","10":"Services"}
S = [
# ---- 04 Business, administration and law (SKA's core) ----
("04","AI Technology and Integration for Business","ai_foundations_for_business ai_tools_and_platforms prompt_design_for_revenue_teams ai_data_privacy_and_governance ai_sales_workflow_integration ai_crm_integration ai_sales_agents_deployment ai_content_marketing_systems ai_marketing_automation_integration ai_personalization_and_segmentation ai_business_process_automation ai_integration_architecture ai_roi_and_change_management blockchain_fundamentals_for_business crypto_payments_integration crypto_compliance_and_risk ai_for_crypto_market_analysis"),
("04","AI-Powered Selling","ai_agent_orchestration_sales ai_assisted_prospecting ai_call_preparation ai_ethics_in_selling ai_objection_simulation ai_pipeline_forecasting ai_proposal_generation ai_sales_research human_ai_handoff prompt_engineering_for_sales"),
("04","Professional Selling","sales consultative_selling closing_techniques objection_handling discovery_questioning rapport_building value_articulation sales_demo_mastery sales_scripting tonality_and_voice followup_systems enterprise_b2b_selling multithreading_deals procurement_navigation deal_qualification_frameworks upsell_cross_sell referral_generation"),
("04","Sales Prospecting and Outbound","outbound_prospecting outbound_sequencing prospecting_systems cold_calling_mastery cold_email_deliverability linkedin_prospecting list_building lead_enrichment intent_data_signals icp_definition sales_cadence_design"),
("04","Sales Management and Revenue Operations","sdr_management pipeline_management territory_planning revenue_operations revenue_forecasting kpi_frameworks okr_goal_systems"),
("04","Sales Psychology","sales_psychology buyer_psychology"),
("04","Negotiation","negotiation advanced_negotiation sales_negotiation_tactics real_estate_negotiation"),
("04","Pricing Strategy","pricing_psychology pricing_conversations price_elasticity_analysis packaging_and_tiers discount_strategy usage_based_pricing margin_management"),
("04","SaaS and Subscription Economics","saas_metrics subscription_economics ltv_modeling churn_reduction expansion_revenue"),
("04","Principles of Marketing","marketing product_marketing positioning_strategy brand_management brand_narrative brand_positioning_strategy"),
("04","Digital Marketing","digital_marketing seo social_media_marketing content_marketing affiliate_marketing influencer_marketing short_form_video_strategy creator_economy social_listening media_buying landing_page_design lead_magnet_design social_media_strategy content_strategy"),
("04","Marketing Analytics and Growth","growth_marketing marketing_analytics marketing_attribution attribution_modeling funnel_analytics ab_testing_statistics experiment_design conversion_rate_optimization checkout_optimization cart_abandonment_recovery pricing_page_design activation_metrics cohort_retention_analysis funnel_architecture audience_analytics"),
("04","Marketing Automation and Demand Generation","marketing_automation demand_generation lifecycle_marketing account_based_marketing campaign_planning content_calendar_systems event_marketing community_marketing community_management engagement_strategy customer_journey_mapping"),
("04","Advertising and Copywriting","advertising copywriting_conversion"),
("04","Public Relations and Corporate Communications","public_relations crisis_communications corporate_communications reputation_management"),
("04","Introduction to Business","business_fundamentals"),
("04","Entrepreneurship","entrepreneurship startup_funding franchise_development mvp_design dropshipping"),
("04","Management and Organizational Behavior","management organizational_behavior organizational_design"),
("04","Leadership","leadership executive_decision_making executive_communication crisis_leadership succession_planning board_management"),
("04","Business Strategy","business_strategy corporate_strategy strategic_management competitive_analysis competitive_intelligence market_intelligence strategic_intelligence systems_thinking consulting"),
("04","Business Analytics and Intelligence","business_analytics business_intelligence dashboard_design knowledge_management"),
("04","Accounting","accounting financial_accounting managerial_accounting"),
("04","Corporate Finance","corporate_finance capital_allocation shareholder_value investor_relations mergers_acquisitions ma_strategy due_diligence_research private_equity venture_capital"),
("04","Investments","investment_analysis portfolio_management stock_market fundamental_analysis technical_analysis options_trading futures_trading forex_trading reit_analysis"),
("04","Banking and Insurance","banking insurance insurance_finance insurance_licensing mortgage_lending"),
("04","Personal Finance","personal_finance financial_planning tax_planning wealth_management retirement_planning financial_literacy"),
("04","Risk Management","risk_management"),
("04","Financial Technology","fintech fintech_systems"),
("04","Cryptocurrency and Digital Assets","cryptocurrency defi nft_digital_assets tokenomics_defi"),
("04","Financial Regulation and Compliance","financial_regulations compliance_finance"),
("04","Operations Management","operations_management"),
("04","Supply Chain Management","supply_chain supply_chain_strategy supply_chain_management procurement vendor_management demand_forecasting inventory_optimization supply_chain_analytics supply_chain_risk supply_chain_resilience lean_supply_chain sustainable_supply_chains"),
("04","Logistics","logistics logistics_operations warehouse_management transportation_management freight_management last_mile_delivery cold_chain_logistics reverse_logistics global_trade_logistics customs_brokerage"),
("04","Project Management","project_management agile_scrum"),
("04","Product Management","product_management technical_product_management product_roadmapping product_launch_strategy user_onboarding_design"),
("04","Human Resource Management","human_resources talent_management"),
("04","International Business and Trade","international_business import_export trade_finance"),
("04","E-Commerce","e_commerce"),
("04","Business Law","business_law contract_law intellectual_property_business"),
("04","Corporate Governance and Business Ethics","corporate_governance business_ethics"),
("04","Sustainable Business","sustainability_business circular_economy carbon_management sustainability_metrics"),
("04","Real Estate Principles","real_estate real_estate_licensing real_estate_fundamentals residential_real_estate commercial_real_estate real_estate_marketing"),
("04","Real Estate Investment and Finance","real_estate_investment real_estate_finance"),
("04","Real Estate Development and Property Management","real_estate_development construction_management_re property_management"),
("04","Property Valuation and Inspection","property_valuation real_estate_appraisal home_inspection"),
("04","Introduction to Law","legal_fundamentals legal_research legal_writing"),
("04","Constitutional Law","constitutional_law"),
("04","Criminal Law and Justice","criminal_law criminal_justice"),
("04","Civil Law and Procedure","civil_law trial_advocacy"),
("04","Contract Law","contract_law_legal"),
("04","Torts","tort_law"),
("04","Property and Land Use Law","property_law real_estate_law land_use_planning"),
("04","Family Law","family_law"),
("04","Immigration Law","immigration_law"),
("04","Corporate and Securities Law","corporate_law securities_law antitrust_law bankruptcy_law"),
("04","Tax Law","tax_law"),
("04","Intellectual Property Law","intellectual_property_law patent_law trademark_law copyright_law"),
("04","Employment and Labor Law","employment_law labor_law"),
("04","Environmental Law","environmental_law"),
("04","Health Law","health_law"),
("04","Technology, Privacy and Media Law","cyber_law data_protection_law media_law"),
("04","International Law and Human Rights","international_law human_rights_law maritime_law"),
("04","Administrative Law","administrative_law"),
("04","Dispute Resolution","mediation_arbitration"),
# ---- 03 Social sciences, journalism and information ----
("03","Microeconomics","microeconomics"),
("03","Macroeconomics","macroeconomics monetary_economics fiscal_policy monetary_policy"),
("03","Econometrics","econometrics"),
("03","Behavioral Economics and Finance","behavioral_economics behavioral_finance"),
("03","Development Economics","development_economics"),
("03","International Economics","international_economics"),
("03","Labor Economics","labor_economics"),
("03","Public Economics","public_economics"),
("03","Health Economics","health_economics"),
("03","Environmental Economics","environmental_economics"),
("03","Economic History","economic_history economic_history_hum"),
("03","Introduction to Psychology","psychology_general"),
("03","Cognitive Psychology","cognitive_psychology cognitive_science"),
("03","Behavioral Psychology","behavioral_psychology"),
("03","Developmental Psychology","developmental_psychology"),
("03","Social Psychology","social_psychology"),
("03","Clinical and Abnormal Psychology","clinical_psychology abnormal_psychology neuropsychology"),
("03","Forensic Psychology","forensic_psychology"),
("03","Educational Psychology","educational_psychology educational_psychology_ed"),
("03","Industrial-Organizational Psychology","industrial_organizational_psych"),
("03","Positive and Health Psychology","positive_psychology health_psychology"),
("03","Sociology","sociology social_theory"),
("03","Research Methods","research_methods_social educational_research"),
("03","Criminology","criminology"),
("03","Demography","demography"),
("03","Urban Studies and Planning","urban_studies urban_planning urban_planning_design urban_sustainability"),
("03","Political Science","political_science comparative_politics"),
("03","International Relations","international_relations diplomacy geopolitics geopolitical_strategy"),
("03","Public Policy and Administration","public_policy public_administration"),
("03","Geography","geography human_geography"),
("03","GIS and Cartography","gis_mapping cartography_gis surveying"),
("03","Communication Studies","communication_studies communication_theory"),
("03","Media Studies","media_studies media_ethics"),
("03","Journalism","journalism photojournalism sports_journalism source_verification"),
("03","Broadcasting and Digital Media Production","broadcasting digital_media_production"),
("03","Library and Information Science","library_science information_science"),
("03","Futures Studies","futurism_futures_studies"),
# ---- 02 Arts and humanities ----
("02","Introduction to Philosophy","philosophy_intro western_philosophy"),
("02","Ethics","ethics ethics_moral_philosophy"),
("02","Metaphysics and Epistemology","metaphysics epistemology"),
("02","Logic","logic_philosophy"),
("02","Philosophy of Mind","philosophy_mind philosophy_of_mind"),
("02","Philosophy of Science","philosophy_science philosophy_of_science"),
("02","Philosophy of Language","philosophy_of_language"),
("02","Political Philosophy","political_philosophy"),
("02","History of Philosophy","ancient_philosophy modern_philosophy existentialism eastern_philosophy stoicism"),
("02","Aesthetics and Art Criticism","aesthetics art_criticism"),
("02","World History","history_world"),
("02","Ancient History","history_ancient ancient_china_civilization ancient_egypt_civilization ancient_india_civilization ancient_mesoamerica ancient_mesopotamia roman_civilization prehistory_human_origins classical_studies classics"),
("02","Medieval History","history_medieval medieval_studies byzantine_empire viking_norse_history"),
("02","Renaissance and Early Modern History","history_renaissance renaissance_studies ottoman_empire"),
("02","Modern History","history_modern"),
("02","American History","history_american"),
("02","European History","history_european"),
("02","Asian History","history_asian"),
("02","African History","history_african"),
("02","Latin American History","history_latin_american"),
("02","Middle Eastern History","history_middle_east"),
("02","Military History","military_history military_history_studies"),
("02","History of Science and Exploration","history_science space_exploration_history"),
("02","Art History","history_art art_history"),
("02","Archaeology","archaeology"),
("02","Anthropology","anthropology cultural_anthropology physical_anthropology indigenous_studies_global"),
("02","Religious Studies","religious_studies theology comparative_religion world_religions buddhism christianity_studies hinduism_studies islam_studies judaism_studies taoism"),
("02","Mythology and Folklore","mythology folklore_mythology comparative_mythology astrology_cultural_history"),
("02","Gender, Ethnic and Disability Studies","gender_studies ethnic_studies disability_studies postcolonial_theory"),
("02","English Grammar and Composition","english_grammar english_composition"),
("02","English Literature","english_literature british_literature"),
("02","American Literature","american_literature"),
("02","World Literature and Poetry","world_literature poetry_poetics"),
("02","Creative Writing","creative_writing screenwriting playwriting"),
("02","Technical and Business Writing","technical_writing business_writing technical_writing_advanced speech_writing"),
("02","Public Speaking and Rhetoric","public_speaking rhetoric debate"),
("02","Spanish","spanish"),("02","French","french"),("02","German","german"),("02","Italian","italian"),
("02","Portuguese","portuguese"),("02","Mandarin Chinese","mandarin_chinese"),("02","Japanese","japanese"),
("02","Korean","korean"),("02","Arabic","arabic"),("02","Hindi","hindi"),("02","Russian","russian"),
("02","Turkish","turkish"),("02","Vietnamese","vietnamese"),("02","Thai","thai"),("02","Swahili","swahili"),
("02","Classical Languages","latin ancient_greek hebrew sanskrit"),
("02","Sign Language and Accessible Communication","sign_language sign_language_communication braille_accessibility"),
("02","Linguistics","linguistics linguistics_applied phonetics_phonology syntax semantics_pragmatics sociolinguistics psycholinguistics linguistics_historical corpus_linguistics computational_linguistics"),
("02","Translation and Interpretation","translation_interpretation"),
("02","Drawing and Illustration","art_fundamentals drawing illustration"),
("02","Painting","painting"),
("02","Sculpture, Ceramics and Printmaking","sculpture ceramics printmaking"),
("02","Photography","photography"),
("02","Digital Art and Animation","digital_art animation"),
("02","Graphic Design and Typography","graphic_design typography_design typography"),
("02","Film Studies","film_studies"),
("02","Filmmaking and Video Production","filmmaking film_directing cinematography video_editing documentary_filmmaking television_film_production"),
("02","Audio Production and Podcasting","sound_design music_production podcasting podcast_production"),
("02","Museum Studies and Conservation","museum_studies art_conservation"),
("02","Music Theory and Composition","music_theory music_composition orchestration"),
("02","Instrumental and Vocal Performance","piano guitar voice drums"),
("02","Music History and Ethnomusicology","music_history ethnomusicology"),
("02","Theater","theater_studies acting directing_theater stagecraft"),
("02","Dance","dance"),
("02","Fashion Design","fashion_design"),
("02","Interior Design","interior_design"),
("02","Industrial Design","industrial_design"),
# ---- 05 Natural sciences, mathematics and statistics ----
("05","Foundations of Mathematics","arithmetic pre_algebra"),
("05","Algebra","algebra_1 algebra_2"),
("05","Geometry and Trigonometry","geometry trigonometry"),
("05","Precalculus","precalculus"),
("05","Calculus","calculus_1 calculus_2 calculus_3"),
("05","Differential Equations","differential_equations"),
("05","Linear Algebra","linear_algebra"),
("05","Abstract Algebra","abstract_algebra representation_theory"),
("05","Algebraic Geometry","algebraic_geometry arithmetic_geometry derived_algebraic_geometry tropical_geometry motivic_cohomology"),
("05","Number Theory","number_theory langlands_program"),
("05","Discrete Mathematics and Logic","discrete_mathematics graph_theory combinatorics set_theory mathematical_logic model_theory"),
("05","Probability and Statistics","probability statistics bayesian_statistics stochastic_analysis"),
("05","Mathematical Analysis","real_analysis complex_analysis functional_analysis measure_theory ergodic_theory operator_algebras"),
("05","Topology","topology geometric_group_theory higher_category_theory homotopy_type_theory"),
("05","Numerical Analysis","numerical_methods numerical_analysis"),
("05","Applied Mathematics and Operations Research","applied_mathematics mathematical_modeling operations_research decision_science game_theory"),
("05","Financial and Actuarial Mathematics","financial_mathematics actuarial_mathematics financial_engineering"),
("05","Theory of Computation and Information","computational_complexity information_theory cryptography_math"),
("05","Classical Mechanics","physics_mechanics classical_mechanics_advanced"),
("05","Thermodynamics and Statistical Mechanics","physics_thermodynamics statistical_mechanics quantum_thermodynamics"),
("05","Electromagnetism","physics_electromagnetism"),
("05","Waves and Optics","physics_optics physics_waves quantum_optics plasmonics metamaterials"),
("05","Quantum Mechanics","quantum_mechanics quantum_information cold_atom_physics attosecond_physics"),
("05","Relativity and Gravitation","relativity gravitational_wave_astronomy quantum_gravity_phenomenology loop_quantum_gravity"),
("05","Nuclear and Particle Physics","nuclear_physics particle_physics quantum_chromodynamics quantum_field_theory string_theory string_theory_physics"),
("05","Condensed Matter Physics","condensed_matter condensed_matter_physics spintronics topological_insulators materials_physics"),
("05","Plasma Physics","plasma_physics fusion_plasma_physics"),
("05","Astronomy and Astrophysics","astronomy astrophysics cosmology planetary_science exoplanet_science astrobiology"),
("05","General Chemistry","chemistry_general chemistry_nuclear"),
("05","Organic Chemistry","chemistry_organic chemistry_polymer"),
("05","Inorganic Chemistry","chemistry_inorganic"),
("05","Physical Chemistry","chemistry_physical"),
("05","Analytical Chemistry","chemistry_analytical"),
("05","Biochemistry","biochemistry"),
("05","Environmental and Green Chemistry","chemistry_environmental green_chemistry"),
("05","Materials Science and Nanotechnology","materials_science nanotechnology molecular_nanotechnology"),
("05","Earth Science and Geology","earth_science geology volcanology_seismology geophysics paleontology_fossils"),
("05","Atmospheric Science and Meteorology","meteorology atmospheric_science"),
("05","Oceanography","oceanography"),
("05","Environmental Science","environmental_science"),
("05","Climate Science","climate_science climate_modeling climate_adaptation climate_engineering"),
("05","General Biology","biology_general"),
("05","Cell and Molecular Biology","cell_biology molecular_biology metabolomics cryo_electron_microscopy protein_folding_prediction"),
("05","Genetics","genetics epigenetics_advanced crispr_gene_editing"),
("05","Bioinformatics and Genomics","bioinformatics bioinformatics_genomics phylogenomics single_cell_genomics dna_data_storage"),
("05","Evolutionary Biology","evolution"),
("05","Microbiology","microbiology virology parasitology mycology"),
("05","Immunology","immunology"),
("05","Botany","botany"),
("05","Zoology","zoology entomology ornithology marine_biology"),
("05","Neuroscience","neuroscience computational_neuroscience connectomics optogenetics cognitive_neuroscience"),
("05","Biotechnology and Synthetic Biology","biotechnology synthetic_biology xenobiology organoid_engineering biophotonics"),
("05","Developmental Biology","developmental_biology"),
("05","Ecology and Conservation","ecology ecology_advanced conservation_biology wildlife_management ocean_conservation"),
("05","Systems Biology","systems_biology"),
# ---- 06 ICT ----
("06","Introduction to Computing and Programming","computer_fundamentals programming_basics"),
("06","Python Programming","python"),
("06","JavaScript, TypeScript and Node.js","javascript typescript nodejs"),
("06","Java and Kotlin","java kotlin"),
("06","C and C++","cpp"),
("06","C# and .NET","csharp"),
("06","Rust and Go","rust go"),
("06","Ruby and PHP","ruby php"),
("06","Mobile App Development","swift mobile_development mobile_app_development"),
("06","Web Development","html_css react angular vue web_design"),
("06","Data Structures and Algorithms","data_structures algorithms"),
("06","Databases","database_design sql nosql"),
("06","Operating Systems","operating_systems"),
("06","Computer Networks","computer_networks"),
("06","Cybersecurity","cybersecurity information_security penetration_testing digital_forensics_advanced cyber_defense zero_trust_architecture identity_access_management oauth_identity security_compliance_frameworks threat_intelligence_analysis incident_response"),
("06","Cryptography","cryptography applied_cryptography advanced_cryptography homomorphic_encryption zero_knowledge_proofs"),
("06","Cloud Computing and DevOps","cloud_computing devops docker_kubernetes devops_engineering devops_culture site_reliability_engineering cloud_native_architecture"),
("06","Software Architecture and System Design","system_design microservices api_design distributed_systems message_queues system_integration_patterns webhook_architecture"),
("06","Software Engineering","software_engineering agile_methodology version_control_git formal_verification program_synthesis"),
("06","Compilers and Programming Languages","compiler_design compilers type_theory category_theory_cs differentiable_programming"),
("06","Computer Architecture","computer_architecture parallel_computing neuromorphic_computing photonic_computing"),
("06","Artificial Intelligence","artificial_intelligence_foundations autonomous_systems enterprise_ai_architecture ai_ethics_governance mechanistic_interpretability"),
("06","Machine Learning","machine_learning deep_learning reinforcement_learning graph_neural_networks federated_learning neural_architecture_search spiking_neural_networks causal_inference_ml"),
("06","Generative AI and Large Language Models","generative_ai_systems large_language_models diffusion_models prompt_engineering natural_language_processing"),
("06","Computer Vision","computer_vision computer_vision_ai"),
("06","Data Science","data_science predictive_analytics"),
("06","Data Engineering","data_engineering big_data data_pipeline_design"),
("06","Blockchain and Web3 Development","blockchain blockchain_development web3"),
("06","Quantum Computing","quantum_computing quantum_computing_applications quantum_machine_learning quantum_error_correction topological_quantum_computing quantum_engineering"),
("06","Embedded Systems and IoT","embedded_systems iot_programming"),
("06","Game Development","game_development game_design"),
("06","Computer Graphics and Extended Reality","computer_graphics ar_vr_development"),
("06","Human-Computer Interaction and UX","human_computer_interaction ui_ux_design user_research_methods"),
("06","No-Code and Low-Code Development","no_code_low_code"),
# ---- 07 Engineering, manufacturing and construction ----
("07","Engineering Fundamentals","engineering_fundamentals"),
("07","Mechanical Engineering","mechanical_engineering"),
("07","Electrical and Power Engineering","electrical_engineering power_systems"),
("07","Electronics and Microsystems","electronics vlsi_design mems_nems"),
("07","Civil and Structural Engineering","civil_engineering structural_engineering geotechnical_engineering transportation_engineering water_resources_engineering"),
("07","Chemical and Petroleum Engineering","chemical_engineering petroleum_engineering"),
("07","Aerospace Engineering","aerospace_engineering aerospace_propulsion_advanced hypersonics aerodynamics flight_mechanics aerospace_propulsion aerospace_materials rocket_science spacecraft_design space_systems_engineering orbital_mechanics"),
("07","Biomedical Engineering","biomedical_engineering brain_computer_interfaces tissue_engineering microfluidics neuroprosthetics"),
("07","Environmental Engineering","environmental_engineering water_treatment waste_management"),
("07","Industrial and Systems Engineering","industrial_engineering systems_engineering quality_engineering six_sigma reliability_engineering fault_tolerant_systems digital_twins"),
("07","Nuclear Engineering","nuclear_engineering"),
("07","Mining Engineering","mining_engineering"),
("07","Agricultural Engineering","agricultural_engineering agricultural_engineering_ag irrigation_science irrigation_engineering precision_agriculture"),
("07","Marine and Ocean Engineering","marine_engineering ocean_engineering"),
("07","Control Systems","control_systems"),
("07","Signal Processing and Telecommunications","signal_processing telecommunications satellite_communications"),
("07","Manufacturing Engineering","manufacturing_engineering cad_cam additive_manufacturing_advanced additive_manufacturing_3d cnc_programming machining"),
("07","Materials Engineering","materials_engineering"),
("07","Photonics","photonics nanophotonics"),
("07","Robotics and Autonomous Vehicles","robotics_programming robotics_engineering soft_robotics swarm_robotics mechatronics autonomous_vehicles_tech"),
("07","Unmanned Aerial Systems","drone_technology unmanned_aerial_systems"),
("07","Renewable Energy Systems","renewable_energy solar_energy_systems wind_energy energy_storage"),
("07","Architecture and Green Building","architecture green_building"),
("07","Landscape Architecture","landscape_architecture landscaping"),
("07","Aircraft Systems and Maintenance","aircraft_systems avionics aircraft_maintenance"),
("07","Electrical Trade","electrical_work"),("07","Plumbing","plumbing"),("07","Welding","welding"),("07","HVAC","hvac"),
("07","Carpentry and Woodworking","carpentry woodworking"),
("07","Building Trades: Masonry, Roofing and Painting","masonry roofing painting_trades"),
("07","Automotive and Diesel Technology","auto_mechanics diesel_mechanics"),
("07","Food Science and Technology","food_science food_technology food_safety brewing_fermentation_science"),
# ---- 08 Agriculture, forestry, fisheries and veterinary ----
("08","Agricultural and Crop Science","agriculture agriculture_fundamentals agronomy crop_science seed_technology weed_science horticulture"),
("08","Soil Science","soil_science"),
("08","Animal Science","animal_science animal_husbandry dairy_science poultry_science apiculture"),
("08","Aquaculture","aquaculture"),
("08","Forestry and Rangeland Management","forestry agroforestry range_management"),
("08","Sustainable and Organic Agriculture","organic_farming sustainable_agriculture permaculture regenerative_agriculture"),
("08","Plant Protection and Agricultural Biotechnology","agricultural_biotechnology plant_pathology pest_management"),
("08","Viticulture and Enology","viticulture wine_viticulture_enology"),
("08","Agricultural Economics and Agribusiness","agricultural_economics agribusiness farm_management"),
("08","Veterinary Science","veterinary_science veterinary_technician"),
# ---- 09 Health and welfare ----
("09","Anatomy and Physiology","anatomy_physiology human_anatomy human_physiology"),
("09","Pathology","pathology"),
("09","Internal Medicine","internal_medicine cardiology endocrinology gastroenterology pulmonology nephrology hematology infectious_disease"),
("09","Surgery","surgery_fundamentals orthopedics urology anesthesiology"),
("09","Pediatrics","pediatrics"),
("09","Obstetrics and Gynecology","obstetrics_gynecology"),
("09","Psychiatry and Mental Health","psychiatry mental_health addiction_science"),
("09","Radiology and Medical Imaging","radiology radiogenomics radiology_technician"),
("09","Emergency Medicine","emergency_medicine emt_paramedic"),
("09","Neurology","neurology"),
("09","Oncology","oncology precision_oncology immunotherapy_advanced"),
("09","Dermatology","dermatology"),
("09","Ophthalmology","ophthalmology"),
("09","Nursing and Clinical Support","nursing medical_assisting phlebotomy"),
("09","Public Health and Epidemiology","public_health epidemiology epidemiology_medical"),
("09","Pharmacology and Toxicology","pharmacology pharmacology_medical toxicology pharmacogenomics pharmacy_technician"),
("09","Bioethics and Medical Ethics","medical_ethics bioethics"),
("09","Clinical Research","clinical_research"),
("09","Health Informatics and Telemedicine","telemedicine health_informatics"),
("09","Sports Medicine and Athletic Training","sports_medicine athletic_training"),
("09","Rehabilitation Therapies","rehabilitation occupational_therapy physical_therapy speech_pathology"),
("09","Dentistry and Oral Health","dental_science dentistry_oral_health dental_hygiene"),
("09","Complementary and Alternative Medicine","alternative_medicine"),
("09","Geriatrics, Aging and Palliative Care","geriatrics aging_gerontology_science palliative_care death_dying_studies biohacking_longevity"),
("09","Regenerative Medicine and Gene Therapy","regenerative_medicine gene_therapy nanomedicine"),
("09","Nutrition Science","nutrition_science nutrition_medical sports_nutrition nutrition_wellness"),
("09","Exercise Science and Kinesiology","exercise_science kinesiology biomechanics strength_conditioning"),
("09","Social Work and Community Development","social_work community_development"),
# ---- 01 Education ----
("01","Pedagogy and Instructional Design","pedagogy curriculum_design online_learning_design educational_technology"),
("01","Teaching in Schools","classroom_management elementary_education secondary_education stem_education multicultural_education literacy_education"),
("01","Early Childhood Education","early_childhood_education"),
("01","Assessment and Evaluation","assessment_evaluation"),
("01","Special and Gifted Education","special_education gifted_education"),
("01","Higher and Adult Education","higher_education_admin adult_education"),
("01","Educational Leadership and Policy","educational_leadership education_policy school_counseling"),
("01","Teaching English as a Second Language","esl_teaching"),
# ---- 10 Services ----
("10","Hospitality Management","hotel_management resort_management guest_relations hospitality_marketing revenue_management_hospitality hospitality_law casino_management cruise_line_management spa_management"),
("10","Restaurant Management","restaurant_management food_beverage_management"),
("10","Tourism Management","tourism_planning travel_agency_operations sustainable_tourism heritage_tourism adventure_tourism"),
("10","Event Management","event_management"),
("10","Culinary Arts","culinary_arts baking_pastry"),
("10","Cosmetology and Barbering","cosmetology barbering esthetician"),
("10","Sports Management","sports_management recreation_management sports_marketing sports_law_ethics esports_management youth_sports_development esports_competitive_gaming"),
("10","Sports Science and Analytics","sports_analytics performance_analysis sports_psychology coaching_methodology"),
("10","Physical Fitness","physical_fitness fitness_programming"),
("10","Aviation Operations and Pilot Training","aviation_pilot flight_navigation aviation_meteorology air_traffic_control human_factors_aviation aviation_safety"),
("10","Aviation Management","aviation_law airport_management"),
("10","Commercial Driving","commercial_driving"),
("10","Maritime Operations","marine_operations naval_science"),
("10","Firefighting","firefighting"),
("10","Law Enforcement","law_enforcement"),
("10","Forensic Science","forensic_science"),
("10","Military Strategy and Leadership","military_strategy military_tactics military_leadership"),
("10","National Security and Intelligence","national_security intelligence_analysis counterterrorism"),
("10","Military Science","military_logistics air_force_science military_law veterans_affairs peacekeeping weapons_systems directed_energy_systems"),
("10","Environmental Policy and Management","environmental_policy environmental_justice environmental_impact_assessment"),
# ---- 00 Generic programmes (personal skills) ----
("00","Critical Thinking and Problem Solving","critical_thinking problem_solving decision_making creative_thinking innovation_methods"),
("00","Emotional Intelligence and Relationships","emotional_intelligence interpersonal_skills relationship_skills conflict_resolution parenting"),
("00","Productivity and Time Management","time_management productivity goal_setting"),
("00","Mindfulness, Stress and Sleep","mindfulness_meditation stress_management sleep_science"),
("00","Communication Skills","communication_skills neurolinguistic_programming"),
("00","Career Development","career_development"),
("00","Study Skills and Learning","study_skills speed_reading memory_techniques"),
]
if __name__ == "__main__":
    cat = json.load(open(sys.argv[1]))["subjects"] if len(sys.argv) > 1 else []
    ids = [c["id"] for c in cat]
    seen = {}
    for f, t, s in S:
        for k in s.split():
            if k in seen: print("DUPLICATE", k, "in", seen[k], "and", t)
            seen[k] = t
    missing = [k for k in ids if k not in seen]
    unknown = [k for k in seen if ids and k not in ids]
    print("real subjects:", len(S), "| topics mapped:", len(seen), "| catalogue:", len(ids), "| missing:", missing, "| not in catalogue:", unknown)
